GET http://localhost:8000/dailyDatas

###
POST http://localhost:8000/dailyDatas
Content-Type: application/json

{
    "bloodSugar": 1.2,
    "weight": 50.1,
    "mood": 5,
    "appetite":5,
    "PatientUuid": "e658a38a-97ec-49a3-adfd-84250e2b8b0b"
}

### 
GET http://localhost:8000/dailyDatas/2b32c018-e8b7-4fdc-89bf-803388aaf996

###

PUT http://localhost:8000/dailyDatas/499198e0-5eec-477f-ae20-bd9cf3643686
Content-Type: application/json

{
    "bloodSugar": 1.2
}
