GET http://localhost:8000/dailyDatas

###
POST http://localhost:8000/dailyDatas
Content-Type: application/json

{
    "bloodSugar": 1.5,
    "weight": 63.7,
    "mood": 2,
    "appetite":1,
    "PatientUuid": "202daa14-e464-464b-b6d5-12d637d5ccb2"
}

### 
GET http://localhost:8000/dailyDatas/2b32c018-e8b7-4fdc-89bf-803388aaf996

###

PUT http://localhost:8000/dailyDatas/499198e0-5eec-477f-ae20-bd9cf3643686
Content-Type: application/json

{
    "bloodSugar": 1.2
}
