GET http://localhost:8080/doctors


###

post http://localhost:8080/doctors
Content-Type: application/json

{
    "firstname": "Jean2",
    "lastname":"David",
    "adress": "3 rue de la fontaine",
    "city":"Biarritz"
}

####
GET http://localhost:8080/doctors/93dfdbe1-487f-489f-bb6a-f758840e9004

###
 
PUT http://localhost:8080/doctors/93dfdbe1-487f-489f-bb6a-f758840e
Content-Type: application/json

{
    "lastname":"Richard",
    "firstname": "Olivier",
    "city":"Biarritz",
    "adress": "3 rue de la fontaine"
}