GET http://localhost:8080/patients

###
POST http://localhost:8080/patients
Content-Type: application/json

{
    "lastname":"toto",
    "firstname":"tata",
    "birthday":"1980/05/29",
    "DoctorUuid": "82e457e3-f730-43a7-aa25-9168855e0dc7"
}

###

GET http://localhost:8080/patients/ce0fa979-f9d4-43fc-b846-565f8df68db2


####
PUT http://localhost:8080/patients/ce0fa979-f9d4-43fc-b846-565f8df68db2
Content-Type: application/json

{
    "lastname": "Hello"
}

###
PUT http://localhost:8080/patients/ce0fa979-f9d4-43fc-b846-565f8df68db2/click
